### ISSUE TITLE
index() method unexpected error :)

### ISSUE THREAD

**Issue by ozgurturkiye** [ozgurturkiye/istihzapython#4]
#### index() - ornek_3 (Var bir sıkıntısı hata verebiliyor)

kardiz = input("Metin girin: ")
aranacak = input("Aradığınız harf: ")

for i in range(len(kardiz)):
    print("i'nin değeri: ", i)
    if i == kardiz.index(aranacak, i):
        print("%s. sırada 1 adet %s harfi bulunuyor" %(i, aranacak))
    else:
        print("%s. sırada %s harfi bulunmuyor" %(i, aranacak))
# other version

kardiz = input("Metin girin: ")
aranacak = input("Aradığınız harf: ")

for i in range(len(kardiz)):
    print(kardiz.index(aranacak, i))
# Hatanın çözümü bulunamadı
# Eğer aranacak karakter son harf değilse hata verip program pıtlıyor...

**Comment by ozgurturkiye** [comment]
@hurol

**Comment by hurturkiye** [comment]
ewt çok hoş diil mi :)

**Comment by hurturkiye** [comment]
istihza Yönetici  Yunus Emre • 5 ay önce
Bu hata normal. Çünkü index() metodu bir karakter dizisini sorgularken, o karakter dizisini bulamadığı noktada hata verir. Yani eğer aranan harf metin içinde geçiyorsa, o harfin geçtiği yerleri belirtir, ama aranan harfi metin içinde bulamadığı bir noktaya ulaştığında da bu hatayı verir. Bu hatayı engellemek için try except bloklarından yararlanabilirsiniz. index() metodunun bu özelliğinden bu belge içinde bahsetmiştim.

**Comment by ozgurturkiye** [comment]
@hurol index() fonksiyonunu kullanmadan çözüm yollarından biri

`
kardiz = input("Metni giriniz")
aranacak = input("Aranacak harfi giriniz")

a = 0

while a < len(kardiz):
    if kardiz[a] == aranacak:
        print("{}.harf {} ile eşleşti".format(a, aranacak))
    else:
        print("{}.harf eşleşmedi".format(a))
    a += 1
`
