### ISSUE TITLE
003.Nufus_Cuzdani

### ISSUE THREAD

**Issue by hurturkiye** [ozgurturkiye/istihzapython#5]
Şu üç tırnaklı haliyle bile zor oldu.
Girilen ad veya soyad'ların uzunluğuna göre sağdaki \* karakteri kayma yapıyor. Galiba rjust() kullanmak gerek :)

**Comment by ozgurturkiye** [comment]
Düzenleme yaptım, format metodu kullanarak birkaç değişiklik ile çözüldü.
